title: FSOFT Oil and Gas
logo: /assets/img/des.jpg
description: FSOFT Oil and Gas SME knowledge sharing pages. Information and photos displayed here are sourced from the internet, and maybe subjected to copyright by their respective site's owner.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

